rvm:
- 2.1.7
script: bundle exec rake test:units
cache: bundler
notifications:
  slack:
    secure: kQeANhtcKjBwtBbIrz9+ATyRzRsuL3uz6I0t+vs94LbBDKry3rOI253lj3EI9WaHdzTTd3FdbMIiLxm8BL+c1ANE/xDmrvEqU+jsXAMyLpuTvwqN+Ne7AfA+3tRCxPJrJC1Zje+nPyjueQOdQbO7sut19G4909x3STA/StAZNik=
